apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kube-system is a system namespace; do NOT declare it here.

helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server
    version: 3.12.2
    releaseName: metrics-server
    namespace: kube-system
    valuesFile: values.yaml
    includeCRDs: true
