helperImage:
  repository: busybox
  tag: 1.36.1

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    memory: 256Mi

helperPod:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
