runtimeClassName: nvidia

tolerations:
  - key: nvidia.com/gpu
    operator: Equal
    value: "present"
    effect: NoSchedule

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: extensions.talos.dev/nvidia-open-gpu-kernel-modules-lts
              operator: Exists
