apiVersion: v1
kind: Namespace
metadata:
  name: tetragon
  labels:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
