extraVolumes:
  - name: debugfs
    hostPath:
      path: /sys/kernel/debug
      type: Directory
  - name: tracefs
    hostPath:
      path: /sys/kernel/tracing
      type: Directory

tetragon:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraVolumeMounts:
    - name: debugfs
      mountPath: /sys/kernel/debug
    - name: tracefs
      mountPath: /sys/kernel/tracing

export:
  stdout:
    enabled: true
    enabledCommand: true
    enabledArgs: true

serviceMonitor:
  enabled: true

tolerations:
  - key: nvidia.com/gpu
    operator: Equal
    value: "present"
    effect: NoSchedule
