apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
  labels:
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
