master:
  replicaCount: 1

worker:
  tolerations:
    - key: nvidia.com/gpu
      operator: Equal
      value: "present"
      effect: NoSchedule
    - key: drbd.linbit.com/lost-quorum
      operator: Exists
      effect: NoSchedule
