apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: vault-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-operator
    helm.sh/chart: vault-operator-1.23.4
  name: vault-operator
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    helm.sh/chart: vault-operator-1.23.4
  name: vault-operator
rules:
  - apiGroups:
      - vault.banzaicloud.com
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - services
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
      - extensions
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - deployments/finalizers
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - get
      - create
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - update
      - list
      - get
      - create
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    helm.sh/chart: vault-operator-1.23.4
  name: vault-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-operator
subjects:
  - kind: ServiceAccount
    name: vault-operator
    namespace: vault
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: vault-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-operator
    helm.sh/chart: vault-operator-1.23.4
  name: vault-operator
  namespace: vault
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: http-metrics
      port: 8383
      protocol: TCP
  selector:
    app.kubernetes.io/name: vault-operator
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: vault-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-operator
    helm.sh/chart: vault-operator-1.23.4
  name: vault-operator
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-operator
        platform.io/capability-consumer.controlplane-egress: "true"
        platform.io/capability-provider.monitoring-scrape: "true"
    spec:
      affinity: {}
      containers:
        - command:
            - vault-operator
            - -sync_period
            - 1m
          env:
            - name: WATCH_NAMESPACE
              value: vault
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: vault-operator
            - name: OPERATOR_LOG_LEVEL
              value: debug
            - name: BANK_VAULTS_IMAGE
              value: ghcr.io/bank-vaults/bank-vaults:v1.32.1
          image: ghcr.io/bank-vaults/vault-operator:v1.23.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: vault-operator
          ports:
            - containerPort: 8080
            - containerPort: 8383
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      serviceAccountName: vault-operator
      terminationGracePeriodSeconds: 10
