apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: vault-operator
    repo: oci://ghcr.io/bank-vaults/helm-charts
    version: 1.23.4
    releaseName: vault-operator
    namespace: vault
    valuesFile: values.yaml
    includeCRDs: true
